apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  KC_HOSTNAME: {{ .Values.keycloak.hostName }}
  KC_DB_USERNAME: {{ .Values.keycloak.databaseUser }}
  KC_DB_URL: {{ .Values.keycloak.databaseUrl }}
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser }}
