apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-keycloak-variables
            - secretRef:
                name: {{ .Release.Name }}-keycloak-passwords
          env:
            - name: KC_HTTP_ENABLED
              value: 'true'
            - name: KC_HOSTNAME_STRICT
              value: 'false'
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: 'false'
            - name: KC_PROXY
              value: edge
      imagePullSecrets:
        - name: {{ .Release.Name }}-harbor
