apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-passwords
type: Opaque
stringData:
{{- if empty .Values.keycloak.adminPassword}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "KEYCLOAK_ADMIN_PASSWORD") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $adminPassword := (get $secretData "KEYCLOAK_ADMIN_PASSWORD") | default (randAlphaNum 16) }}
  KEYCLOAK_ADMIN_PASSWORD: {{ $adminPassword | quote }}
{{- else }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword }}
{{- end }}
  KC_DB_PASSWORD: {{ .Values.mariadb.auth.password }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
metadata:
  name: {{ .Release.Name }}-harbor
