apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-passwords
type: Opaque
stringData:
{{- if empty .Values.keycloak.adminPassword}}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "admin-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $jwtSecret := (get $secretData "admin-password") | default (randAlphaNum 16) }}
  admin-password: {{ $jwtSecret | quote }}
{{- else }}
  admin-password: {{ .Values.keycloak.adminPassword }}
{{- end }}
  db-password: {{ .Values.keycloak.databasePassword }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
metadata:
  name: {{ .Release.Name }}-harbor
