apiVersion: v2
appVersion: "1.16.0"
name: keycloak
description: Keycloak
version: 0.3.2
keywords:
  - keycloak
  - oauth
  - saml
home: https://github.com/lewis-green/charts
sources:
  - https://keycloak.org
  - https://github.com/lewis-green/charts
maintainers:
  - name: Lewis Green
    email: lewis@lewisgreen.co.uk
dependencies:
  - name: mariadb
    version: 11.1.8
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled