ingress:
  className: 
  certManagerIssuer: letsencrypt

image:
  registry: harbor.apps.lewisgreen.co.uk/lewisgreen
  name: keycloak-mariadb
  tag: latest
  pullPolicy: Always
  credentials:
    username: ''
    password: ''

persistence:
  config:
    enabled: false

keycloak:
  hostName: keycloak.local
  adminUser: admin
  adminPassword: 

mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: keycloak
    username: keycloak
    password: keycloakpass
    rootPassword: keycloakrootpass
  primary:
    persistence:
      enabled: false
      storageClass: 
