---
apiVersion: v2
appVersion: 1.0.0
description: MQTT Broker based on Aedes
name: mqtt-broker
version: 1.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - aedes
  - mqtt-broker
  - mqtt
home: https://github.com/lewis-green/charts/tree/main/charts/mqtt-broker
sources:
  - https://github.com/lewis-green/charts/tree/main/charts/mqtt-broker
maintainers:
  - name: lewis-green
    email: lewis@lewisgreen.co.uk
dependencies:
  - name: common
    repository: https://charts.lewisgreen.co.uk
    version: 0.1.0