#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/lewis-green/charts/tree/main/charts/common/values.yaml
#

image:
  # -- image repository
  repository: harbor.apps.lewisgreen.co.uk/lewisgreen/mqtt-broker
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

env:
  MQTT_PORT: 1883
  WS_PORT: 8883
  ENABLE_CLUSTER: 0
  AUTH_BASIC_USER: testuser
  AUTH_BASIC_PASSWORD: testpassword

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sqlsrv.apps.lewisgreen.co.uk
  main:
    type: ClusterIP
    ports:
      http:
        port: 8883
        enabled: false
      mqtt:
        port: 1883
        enabled: true

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
    annotations:
      nginx.org/websocket-services: mqtt-broker
 
